### ISSUE TITLE
Development plans and GitHub release

### ISSUE THREAD

**Issue by baimafeima** [odrevet/moe#1]
What are your plans regarding moe/kanjipad?

**Comment by odrevet** [comment]
I did not build/use this in a while. 
I will build it soon and test it, then I can decide what to do (either release as-is, fix, or un-maintain it)

**Comment by baimafeima** [comment]
Sounds great and I look forward to testing it.

**Comment by odrevet** [comment]
tested and released as is

**Comment by baimafeima** [comment]
@odrevet Thanks a lot. Is the GTK3 rewrite already completed with this release?

**Comment by odrevet** [comment]
absolutly
